Feat bac 73 getinterviewby stack
workshopapps/engineerprofile360.web pull request #658
Opened 2022-12-10 07:14 UTC by VikMaamaa

#### Task reference
Get list of available assessments for admin dashboard

#### How to test
query the endpoint
/api/interview/admin/all
#### References 
![pag](https://user-images.githubusercontent.com/73889664/206837625-56ea94eb-9a96-4b0a-80c0-30ab87bd2e5c.png)

2022-12-10 08:33 UTC, dasaint001 requested changes

2022-12-10 08:33 UTC, dasaint001 commented on backend/app/Http/Controllers/InterviewController.php
> +            return $this->sendResponse(
This block is not needed since you are fetching all

2022-12-10 08:33 UTC, dasaint001 commented on backend/routes/api.php
> +    Route::get('/admin/all', [InterviewController::class, 'getInterviewsAdmin'])->middleware("isloggedin", "isadmin");
this route can not be done this way.. could you please create a sub grouped route for interview within the admin route

2022-12-10 08:33 UTC, dasaint001 commented on backend/app/Http/Controllers/InterviewController.php
> +    {
is there any difference between the getInterviews and this function?

2022-12-10 09:42 UTC, VikMaamaa commented on backend/app/Http/Controllers/InterviewController.php
> +    {
The endpoint is needed, but restricted to only admin
But I do not know whether the unprotected one has been consumed
somewhere else,
So what do you suggest?

2022-12-10 09:42 UTC, VikMaamaa commented on backend/app/Http/Controllers/InterviewController.php
> +    {
The endpoint is needed, but restricted to only admin
But I do not know whether the unprotected one has been consumed
somewhere else,
So what do you suggest?

2022-12-10 12:08 UTC, dasaint001 commented on backend/app/Http/Controllers/InterviewController.php
> +    {
pls you are suppose to confirm that..

2022-12-12 10:12 UTC, dasaint001 commented
PR unattended to

2022-12-12 10:12 UTC, closed without merging